# Generated by Django 5.0.7 on 2024-09-01 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_alter_job_employment_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='job',
            name='salary',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
