# Generated by Django 5.0.7 on 2024-09-18 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_application'),
        ('seeker', '0004_rename_user_experience_seeker'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('job', 'applicant')},
        ),
    ]
